#!/usr/bin/python

import pygtk
pygtk.require('2.0')

import sys
import gtk

remove_newline = False

def main():
    process_args()

    clipboard = gtk.clipboard_get()
    if len(sys.argv) > 1:
        text = ' '.join(sys.argv[1:])
    else:
        text = sys.stdin.read()

    if remove_newline and text[-1] == '\n':
        text = text[:-1]
    clipboard.set_text(text)
    clipboard.store()

def process_args():
    global remove_newline
    if '-r' in sys.argv:
        remove_newline = True
        sys.argv.remove('-r')

if __name__ == '__main__':
    main()
