#!/usr/bin/env python

import sys
import re

def invert_matched_hex(m):
    return str(1 - float(m.group(1)))

xml_color_regex = re.compile(r'(?<=<real>)([^<]+)')

for line in sys.stdin:
    line = xml_color_regex.sub(invert_matched_xml, line)
    print line,
