#!/bin/bash

if [[ $# > 0 ]]; then
	num_words=$1
fi

word_count=$(wc -l /usr/share/dict/words | cut -d' ' -f1)

for i in $(eval echo {1..$num_words}); do
	word_num=$(( ($RANDOM + (32768 * $RANDOM)) % $word_count + 1))
	echo -n "$(sed -n "${word_num}p" /usr/share/dict/words) "
done
echo
